version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - python -m pip install -r requirements/dev.txt
    - python docs/libdoc.py --output $READTHEDOCS_OUTPUT/html/ src/StateMachineLibrary
