version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test-py36:  &build-and-test-template
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements/dev.txt
      - run:
          name: Run pylint
          command: pylint src
      - run:
          name: Run utests
          command: pytest tests/utests
      - run:
          name: Run atests
          command: robot -P src -L DEBUG tests/atests
  build-and-test-py37:
    <<: *build-and-test-template
    docker:
      - image: cimg/python:3.7
  build-and-test-py38:
    <<: *build-and-test-template
    docker:
      - image: cimg/python:3.8
  build-and-test-py39:
    <<: *build-and-test-template
    docker:
      - image: cimg/python:3.9
  build-and-test-py310:
    <<: *build-and-test-template
    docker:
      - image: cimg/python:3.10
  build-and-test-py311:
    <<: *build-and-test-template
    docker:
      - image: cimg/python:3.11
  build-and-test-py312:
    <<: *build-and-test-template
    docker:
      - image: cimg/python:3.12

workflows:
  test:
    jobs:
      - build-and-test-py36
      - build-and-test-py37
      - build-and-test-py38
      - build-and-test-py39
      - build-and-test-py310
      - build-and-test-py311
      - build-and-test-py312
